apiVersion: apps/v1
kind: Deployment
metadata:
  name: watermark-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: watermark-frontend
      tier: frontend
      track: stable
  template:
    metadata:
      labels:
        app: watermark-frontend
        tier: frontend
        track: stable
    spec:
      containers:
        - name: watermark-frontend
          image: gcr.io/watermarking-424614/watermark-frontend
          ports:
            - containerPort: 80
          env:
          - name: CURRENT_ENV
            value: "TEST"
          - name: DATABASE_URL
            value: "postgres://user:password@hostname:5432/dbname"
---
apiVersion: v1
kind: Service
metadata:
   name: watermark-frontend
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: watermark-frontend
    tier: frontend
