apiVersion: apps/v1
kind: Deployment
metadata:
  name: watermark-backend
spec:
  replicas: 5
  selector:
    matchLabels:
      app: watermark-backend
      tier: watermark-backend
      track: stable
  template:
    metadata:
      labels:
        app: watermark-backend
        tier: watermark-backend
        track: stable

    spec:
      containers:
        - name: watermark-backend
          image: gcr.io/watermarking-424614/watermark-backend
          ports:
           - containerPort: 8080
          env:
          - name: CURRENT_ENV
            value: "TEST"
          - name: DATABASE_URL
            value: "postgres://user:password@hostname:5432/dbname"
---
apiVersion: v1
kind: Service
metadata:
  name: watermark-backend
spec:
  selector:
    app: watermark-backend
    tier: watermark-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080